'''
Students require a hashcode (which depends upon their roll number) to enter the library. Generate the hashcode from the given roll number. The process to generate the hash code is given below. 

The hashcode is generated by concatenating the first alphabets of the digits at even places spelled in 
words and the last alphabets of the digits at odd places spelled in words. 
To this branch code is suffixed and the id number of the student is prefixed. 

The roll number of the student consists of the LastTwoDigitsofCurrentYear followed by 
ThreeDigitCollegeCode followed by TwoDigitBranchCode followed ThreeDigitIDNumber.

Input format:
An integer number.

Output format:
Single line of alphanumeric string.

Sample input:
2118523112

Sample output:
23toftoetoeo112

Explanation:
The given roll number is 2118523112. The first alphabet of the digits at even places spelled in words is tofto. And the last alphabet of the digits at odd places spelled in words is etoeo. Concatenating them we get toftoetoeo. Prefixing the branch code and suffixing the id number we get 23toftoetoeo112.

'''

numdict = {'1':'one','2':'two','3':'three','4':'four','5':'five','6':'six','7':'seven','8':'eight','9':'nine','0':'zero'}
strinp = input()
inplist = list(map(str,strinp))


finalstrone= ""
finalstrtwo = ""
for i in range(len(inplist)):
    
    if i % 2 == 0:
        if inplist[i] in numdict:
            a = numdict.get(inplist[i])
            finalstrone = finalstrone + a[0]
    if i % 2 != 0:
        if inplist[i] in numdict:
            a = numdict.get(inplist[i])
            finalstrtwo = finalstrtwo + a[-1]

print(strinp[-5:-3:1]+finalstrone+finalstrtwo+strinp[-3::])